qsub catalysis_variational.pbs
qsub diffusion_loweruppercenters_variational.pbs
qsub diffusion_variational.pbs
#qsub mcmc_catalysis_dimensionless.pbs
#qsub mcmc_diffusion.pbs
#qsub mcmc_upperlowercenters_diffusion.pbs
